/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated.departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSignalsWellbeingRouteImport } from './routes/_authenticated.signals.wellbeing'
import { Route as AuthenticatedSignalsScreeningsRouteImport } from './routes/_authenticated.signals.screenings'
import { Route as AuthenticatedSignalsMoodRouteImport } from './routes/_authenticated.signals.mood'
import { Route as AuthenticatedSignalsHeatmapRouteImport } from './routes/_authenticated.signals.heatmap'
import { Route as AuthenticatedSignalsEngagementRouteImport } from './routes/_authenticated.signals.engagement'
import { Route as AuthenticatedCohortsYearRouteImport } from './routes/_authenticated.cohorts.year'
import { Route as AuthenticatedCohortsDemographicsRouteImport } from './routes/_authenticated.cohorts.demographics'
import { Route as AuthenticatedCohortsCompareRouteImport } from './routes/_authenticated.cohorts.compare'
import { Route as AuthenticatedCareRiskRouteImport } from './routes/_authenticated.care.risk'
import { Route as AuthenticatedCareReferralsRouteImport } from './routes/_authenticated.care.referrals'
import { Route as AuthenticatedCareCapacityRouteImport } from './routes/_authenticated.care.capacity'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated.admin.access'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSignalsWellbeingRoute =
  AuthenticatedSignalsWellbeingRouteImport.update({
    id: '/signals/wellbeing',
    path: '/signals/wellbeing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsScreeningsRoute =
  AuthenticatedSignalsScreeningsRouteImport.update({
    id: '/signals/screenings',
    path: '/signals/screenings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsMoodRoute =
  AuthenticatedSignalsMoodRouteImport.update({
    id: '/signals/mood',
    path: '/signals/mood',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsHeatmapRoute =
  AuthenticatedSignalsHeatmapRouteImport.update({
    id: '/signals/heatmap',
    path: '/signals/heatmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsEngagementRoute =
  AuthenticatedSignalsEngagementRouteImport.update({
    id: '/signals/engagement',
    path: '/signals/engagement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsYearRoute =
  AuthenticatedCohortsYearRouteImport.update({
    id: '/cohorts/year',
    path: '/cohorts/year',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsDemographicsRoute =
  AuthenticatedCohortsDemographicsRouteImport.update({
    id: '/cohorts/demographics',
    path: '/cohorts/demographics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsCompareRoute =
  AuthenticatedCohortsCompareRouteImport.update({
    id: '/cohorts/compare',
    path: '/cohorts/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareRiskRoute = AuthenticatedCareRiskRouteImport.update({
  id: '/care/risk',
  path: '/care/risk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCareReferralsRoute =
  AuthenticatedCareReferralsRouteImport.update({
    id: '/care/referrals',
    path: '/care/referrals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareCapacityRoute =
  AuthenticatedCareCapacityRouteImport.update({
    id: '/care/capacity',
    path: '/care/capacity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/admin/access',
    path: '/admin/access',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/care/capacity': typeof AuthenticatedCareCapacityRoute
  '/care/referrals': typeof AuthenticatedCareReferralsRoute
  '/care/risk': typeof AuthenticatedCareRiskRoute
  '/cohorts/compare': typeof AuthenticatedCohortsCompareRoute
  '/cohorts/demographics': typeof AuthenticatedCohortsDemographicsRoute
  '/cohorts/year': typeof AuthenticatedCohortsYearRoute
  '/signals/engagement': typeof AuthenticatedSignalsEngagementRoute
  '/signals/heatmap': typeof AuthenticatedSignalsHeatmapRoute
  '/signals/mood': typeof AuthenticatedSignalsMoodRoute
  '/signals/screenings': typeof AuthenticatedSignalsScreeningsRoute
  '/signals/wellbeing': typeof AuthenticatedSignalsWellbeingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/care/capacity': typeof AuthenticatedCareCapacityRoute
  '/care/referrals': typeof AuthenticatedCareReferralsRoute
  '/care/risk': typeof AuthenticatedCareRiskRoute
  '/cohorts/compare': typeof AuthenticatedCohortsCompareRoute
  '/cohorts/demographics': typeof AuthenticatedCohortsDemographicsRoute
  '/cohorts/year': typeof AuthenticatedCohortsYearRoute
  '/signals/engagement': typeof AuthenticatedSignalsEngagementRoute
  '/signals/heatmap': typeof AuthenticatedSignalsHeatmapRoute
  '/signals/mood': typeof AuthenticatedSignalsMoodRoute
  '/signals/screenings': typeof AuthenticatedSignalsScreeningsRoute
  '/signals/wellbeing': typeof AuthenticatedSignalsWellbeingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/care/capacity': typeof AuthenticatedCareCapacityRoute
  '/_authenticated/care/referrals': typeof AuthenticatedCareReferralsRoute
  '/_authenticated/care/risk': typeof AuthenticatedCareRiskRoute
  '/_authenticated/cohorts/compare': typeof AuthenticatedCohortsCompareRoute
  '/_authenticated/cohorts/demographics': typeof AuthenticatedCohortsDemographicsRoute
  '/_authenticated/cohorts/year': typeof AuthenticatedCohortsYearRoute
  '/_authenticated/signals/engagement': typeof AuthenticatedSignalsEngagementRoute
  '/_authenticated/signals/heatmap': typeof AuthenticatedSignalsHeatmapRoute
  '/_authenticated/signals/mood': typeof AuthenticatedSignalsMoodRoute
  '/_authenticated/signals/screenings': typeof AuthenticatedSignalsScreeningsRoute
  '/_authenticated/signals/wellbeing': typeof AuthenticatedSignalsWellbeingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/dashboard'
    | '/departments'
    | '/settings/appearance'
    | '/admin/access'
    | '/admin/audit'
    | '/care/capacity'
    | '/care/referrals'
    | '/care/risk'
    | '/cohorts/compare'
    | '/cohorts/demographics'
    | '/cohorts/year'
    | '/signals/engagement'
    | '/signals/heatmap'
    | '/signals/mood'
    | '/signals/screenings'
    | '/signals/wellbeing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/dashboard'
    | '/departments'
    | '/settings/appearance'
    | '/admin/access'
    | '/admin/audit'
    | '/care/capacity'
    | '/care/referrals'
    | '/care/risk'
    | '/cohorts/compare'
    | '/cohorts/demographics'
    | '/cohorts/year'
    | '/signals/engagement'
    | '/signals/heatmap'
    | '/signals/mood'
    | '/signals/screenings'
    | '/signals/wellbeing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/settings'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/settings/appearance'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/audit'
    | '/_authenticated/care/capacity'
    | '/_authenticated/care/referrals'
    | '/_authenticated/care/risk'
    | '/_authenticated/cohorts/compare'
    | '/_authenticated/cohorts/demographics'
    | '/_authenticated/cohorts/year'
    | '/_authenticated/signals/engagement'
    | '/_authenticated/signals/heatmap'
    | '/_authenticated/signals/mood'
    | '/_authenticated/signals/screenings'
    | '/_authenticated/signals/wellbeing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/wellbeing': {
      id: '/_authenticated/signals/wellbeing'
      path: '/signals/wellbeing'
      fullPath: '/signals/wellbeing'
      preLoaderRoute: typeof AuthenticatedSignalsWellbeingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/screenings': {
      id: '/_authenticated/signals/screenings'
      path: '/signals/screenings'
      fullPath: '/signals/screenings'
      preLoaderRoute: typeof AuthenticatedSignalsScreeningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/mood': {
      id: '/_authenticated/signals/mood'
      path: '/signals/mood'
      fullPath: '/signals/mood'
      preLoaderRoute: typeof AuthenticatedSignalsMoodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/heatmap': {
      id: '/_authenticated/signals/heatmap'
      path: '/signals/heatmap'
      fullPath: '/signals/heatmap'
      preLoaderRoute: typeof AuthenticatedSignalsHeatmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/engagement': {
      id: '/_authenticated/signals/engagement'
      path: '/signals/engagement'
      fullPath: '/signals/engagement'
      preLoaderRoute: typeof AuthenticatedSignalsEngagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/year': {
      id: '/_authenticated/cohorts/year'
      path: '/cohorts/year'
      fullPath: '/cohorts/year'
      preLoaderRoute: typeof AuthenticatedCohortsYearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/demographics': {
      id: '/_authenticated/cohorts/demographics'
      path: '/cohorts/demographics'
      fullPath: '/cohorts/demographics'
      preLoaderRoute: typeof AuthenticatedCohortsDemographicsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/compare': {
      id: '/_authenticated/cohorts/compare'
      path: '/cohorts/compare'
      fullPath: '/cohorts/compare'
      preLoaderRoute: typeof AuthenticatedCohortsCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care/risk': {
      id: '/_authenticated/care/risk'
      path: '/care/risk'
      fullPath: '/care/risk'
      preLoaderRoute: typeof AuthenticatedCareRiskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care/referrals': {
      id: '/_authenticated/care/referrals'
      path: '/care/referrals'
      fullPath: '/care/referrals'
      preLoaderRoute: typeof AuthenticatedCareReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care/capacity': {
      id: '/_authenticated/care/capacity'
      path: '/care/capacity'
      fullPath: '/care/capacity'
      preLoaderRoute: typeof AuthenticatedCareCapacityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/admin/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedCareCapacityRoute: typeof AuthenticatedCareCapacityRoute
  AuthenticatedCareReferralsRoute: typeof AuthenticatedCareReferralsRoute
  AuthenticatedCareRiskRoute: typeof AuthenticatedCareRiskRoute
  AuthenticatedCohortsCompareRoute: typeof AuthenticatedCohortsCompareRoute
  AuthenticatedCohortsDemographicsRoute: typeof AuthenticatedCohortsDemographicsRoute
  AuthenticatedCohortsYearRoute: typeof AuthenticatedCohortsYearRoute
  AuthenticatedSignalsEngagementRoute: typeof AuthenticatedSignalsEngagementRoute
  AuthenticatedSignalsHeatmapRoute: typeof AuthenticatedSignalsHeatmapRoute
  AuthenticatedSignalsMoodRoute: typeof AuthenticatedSignalsMoodRoute
  AuthenticatedSignalsScreeningsRoute: typeof AuthenticatedSignalsScreeningsRoute
  AuthenticatedSignalsWellbeingRoute: typeof AuthenticatedSignalsWellbeingRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedCareCapacityRoute: AuthenticatedCareCapacityRoute,
  AuthenticatedCareReferralsRoute: AuthenticatedCareReferralsRoute,
  AuthenticatedCareRiskRoute: AuthenticatedCareRiskRoute,
  AuthenticatedCohortsCompareRoute: AuthenticatedCohortsCompareRoute,
  AuthenticatedCohortsDemographicsRoute: AuthenticatedCohortsDemographicsRoute,
  AuthenticatedCohortsYearRoute: AuthenticatedCohortsYearRoute,
  AuthenticatedSignalsEngagementRoute: AuthenticatedSignalsEngagementRoute,
  AuthenticatedSignalsHeatmapRoute: AuthenticatedSignalsHeatmapRoute,
  AuthenticatedSignalsMoodRoute: AuthenticatedSignalsMoodRoute,
  AuthenticatedSignalsScreeningsRoute: AuthenticatedSignalsScreeningsRoute,
  AuthenticatedSignalsWellbeingRoute: AuthenticatedSignalsWellbeingRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
