/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsNotificationsRouteImport } from './routes/settings.notifications'
import { Route as SettingsAppearanceRouteImport } from './routes/settings.appearance'
import { Route as SettingsAccountRouteImport } from './routes/settings.account'
import { Route as ReportsPrintRouteImport } from './routes/reports.print'
import { Route as AuthenticatedQaDataRouteImport } from './routes/_authenticated.qa-data'
import { Route as AuthenticatedQaRouteImport } from './routes/_authenticated/qa'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedHelpRouteImport } from './routes/_authenticated.help'
import { Route as AuthenticatedDepartmentsRouteImport } from './routes/_authenticated.departments'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated.reports.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated.admin.index'
import { Route as AuthenticatedSignalsWellbeingRouteImport } from './routes/_authenticated.signals.wellbeing'
import { Route as AuthenticatedSignalsSessionsRouteImport } from './routes/_authenticated.signals.sessions'
import { Route as AuthenticatedSignalsScreeningsRouteImport } from './routes/_authenticated.signals.screenings'
import { Route as AuthenticatedSignalsMoodRouteImport } from './routes/_authenticated.signals.mood'
import { Route as AuthenticatedSignalsHeatmapRouteImport } from './routes/_authenticated.signals.heatmap'
import { Route as AuthenticatedSignalsEngagementRouteImport } from './routes/_authenticated.signals.engagement'
import { Route as AuthenticatedReportsHistoryRouteImport } from './routes/_authenticated.reports.history'
import { Route as AuthenticatedCohortsYearRouteImport } from './routes/_authenticated.cohorts.year'
import { Route as AuthenticatedCohortsProgramsRouteImport } from './routes/_authenticated.cohorts.programs'
import { Route as AuthenticatedCohortsDemographicsRouteImport } from './routes/_authenticated.cohorts.demographics'
import { Route as AuthenticatedCohortsCompareRouteImport } from './routes/_authenticated.cohorts.compare'
import { Route as AuthenticatedCareRoutingRouteImport } from './routes/_authenticated.care.routing'
import { Route as AuthenticatedCareRiskRouteImport } from './routes/_authenticated.care.risk'
import { Route as AuthenticatedCareReferralsRouteImport } from './routes/_authenticated.care.referrals'
import { Route as AuthenticatedCareCapacityRouteImport } from './routes/_authenticated.care.capacity'
import { Route as AuthenticatedAdminPoliciesRouteImport } from './routes/_authenticated.admin.policies'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated.admin.members'
import { Route as AuthenticatedAdminInstitutionRouteImport } from './routes/_authenticated.admin.institution'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated.admin.audit'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsNotificationsRoute = SettingsNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsAccountRoute = SettingsAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => SettingsRoute,
} as any)
const ReportsPrintRoute = ReportsPrintRouteImport.update({
  id: '/reports/print',
  path: '/reports/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQaDataRoute = AuthenticatedQaDataRouteImport.update({
  id: '/qa-data',
  path: '/qa-data',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQaRoute = AuthenticatedQaRouteImport.update({
  id: '/qa',
  path: '/qa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHelpRoute = AuthenticatedHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDepartmentsRoute =
  AuthenticatedDepartmentsRouteImport.update({
    id: '/departments',
    path: '/departments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedSignalsWellbeingRoute =
  AuthenticatedSignalsWellbeingRouteImport.update({
    id: '/signals/wellbeing',
    path: '/signals/wellbeing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsSessionsRoute =
  AuthenticatedSignalsSessionsRouteImport.update({
    id: '/signals/sessions',
    path: '/signals/sessions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsScreeningsRoute =
  AuthenticatedSignalsScreeningsRouteImport.update({
    id: '/signals/screenings',
    path: '/signals/screenings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsMoodRoute =
  AuthenticatedSignalsMoodRouteImport.update({
    id: '/signals/mood',
    path: '/signals/mood',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsHeatmapRoute =
  AuthenticatedSignalsHeatmapRouteImport.update({
    id: '/signals/heatmap',
    path: '/signals/heatmap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSignalsEngagementRoute =
  AuthenticatedSignalsEngagementRouteImport.update({
    id: '/signals/engagement',
    path: '/signals/engagement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsHistoryRoute =
  AuthenticatedReportsHistoryRouteImport.update({
    id: '/reports/history',
    path: '/reports/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsYearRoute =
  AuthenticatedCohortsYearRouteImport.update({
    id: '/cohorts/year',
    path: '/cohorts/year',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsProgramsRoute =
  AuthenticatedCohortsProgramsRouteImport.update({
    id: '/cohorts/programs',
    path: '/cohorts/programs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsDemographicsRoute =
  AuthenticatedCohortsDemographicsRouteImport.update({
    id: '/cohorts/demographics',
    path: '/cohorts/demographics',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCohortsCompareRoute =
  AuthenticatedCohortsCompareRouteImport.update({
    id: '/cohorts/compare',
    path: '/cohorts/compare',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareRoutingRoute =
  AuthenticatedCareRoutingRouteImport.update({
    id: '/care/routing',
    path: '/care/routing',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareRiskRoute = AuthenticatedCareRiskRouteImport.update({
  id: '/care/risk',
  path: '/care/risk',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCareReferralsRoute =
  AuthenticatedCareReferralsRouteImport.update({
    id: '/care/referrals',
    path: '/care/referrals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCareCapacityRoute =
  AuthenticatedCareCapacityRouteImport.update({
    id: '/care/capacity',
    path: '/care/capacity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPoliciesRoute =
  AuthenticatedAdminPoliciesRouteImport.update({
    id: '/policies',
    path: '/policies',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInstitutionRoute =
  AuthenticatedAdminInstitutionRouteImport.update({
    id: '/institution',
    path: '/institution',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/qa': typeof AuthenticatedQaRoute
  '/qa-data': typeof AuthenticatedQaDataRoute
  '/reports/print': typeof ReportsPrintRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/institution': typeof AuthenticatedAdminInstitutionRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/care/capacity': typeof AuthenticatedCareCapacityRoute
  '/care/referrals': typeof AuthenticatedCareReferralsRoute
  '/care/risk': typeof AuthenticatedCareRiskRoute
  '/care/routing': typeof AuthenticatedCareRoutingRoute
  '/cohorts/compare': typeof AuthenticatedCohortsCompareRoute
  '/cohorts/demographics': typeof AuthenticatedCohortsDemographicsRoute
  '/cohorts/programs': typeof AuthenticatedCohortsProgramsRoute
  '/cohorts/year': typeof AuthenticatedCohortsYearRoute
  '/reports/history': typeof AuthenticatedReportsHistoryRoute
  '/signals/engagement': typeof AuthenticatedSignalsEngagementRoute
  '/signals/heatmap': typeof AuthenticatedSignalsHeatmapRoute
  '/signals/mood': typeof AuthenticatedSignalsMoodRoute
  '/signals/screenings': typeof AuthenticatedSignalsScreeningsRoute
  '/signals/sessions': typeof AuthenticatedSignalsSessionsRoute
  '/signals/wellbeing': typeof AuthenticatedSignalsWellbeingRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/departments': typeof AuthenticatedDepartmentsRoute
  '/help': typeof AuthenticatedHelpRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/qa': typeof AuthenticatedQaRoute
  '/qa-data': typeof AuthenticatedQaDataRoute
  '/reports/print': typeof ReportsPrintRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/institution': typeof AuthenticatedAdminInstitutionRoute
  '/admin/members': typeof AuthenticatedAdminMembersRoute
  '/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/care/capacity': typeof AuthenticatedCareCapacityRoute
  '/care/referrals': typeof AuthenticatedCareReferralsRoute
  '/care/risk': typeof AuthenticatedCareRiskRoute
  '/care/routing': typeof AuthenticatedCareRoutingRoute
  '/cohorts/compare': typeof AuthenticatedCohortsCompareRoute
  '/cohorts/demographics': typeof AuthenticatedCohortsDemographicsRoute
  '/cohorts/programs': typeof AuthenticatedCohortsProgramsRoute
  '/cohorts/year': typeof AuthenticatedCohortsYearRoute
  '/reports/history': typeof AuthenticatedReportsHistoryRoute
  '/signals/engagement': typeof AuthenticatedSignalsEngagementRoute
  '/signals/heatmap': typeof AuthenticatedSignalsHeatmapRoute
  '/signals/mood': typeof AuthenticatedSignalsMoodRoute
  '/signals/screenings': typeof AuthenticatedSignalsScreeningsRoute
  '/signals/sessions': typeof AuthenticatedSignalsSessionsRoute
  '/signals/wellbeing': typeof AuthenticatedSignalsWellbeingRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/settings': typeof SettingsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/departments': typeof AuthenticatedDepartmentsRoute
  '/_authenticated/help': typeof AuthenticatedHelpRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/qa': typeof AuthenticatedQaRoute
  '/_authenticated/qa-data': typeof AuthenticatedQaDataRoute
  '/reports/print': typeof ReportsPrintRoute
  '/settings/account': typeof SettingsAccountRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/notifications': typeof SettingsNotificationsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/institution': typeof AuthenticatedAdminInstitutionRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRoute
  '/_authenticated/admin/policies': typeof AuthenticatedAdminPoliciesRoute
  '/_authenticated/care/capacity': typeof AuthenticatedCareCapacityRoute
  '/_authenticated/care/referrals': typeof AuthenticatedCareReferralsRoute
  '/_authenticated/care/risk': typeof AuthenticatedCareRiskRoute
  '/_authenticated/care/routing': typeof AuthenticatedCareRoutingRoute
  '/_authenticated/cohorts/compare': typeof AuthenticatedCohortsCompareRoute
  '/_authenticated/cohorts/demographics': typeof AuthenticatedCohortsDemographicsRoute
  '/_authenticated/cohorts/programs': typeof AuthenticatedCohortsProgramsRoute
  '/_authenticated/cohorts/year': typeof AuthenticatedCohortsYearRoute
  '/_authenticated/reports/history': typeof AuthenticatedReportsHistoryRoute
  '/_authenticated/signals/engagement': typeof AuthenticatedSignalsEngagementRoute
  '/_authenticated/signals/heatmap': typeof AuthenticatedSignalsHeatmapRoute
  '/_authenticated/signals/mood': typeof AuthenticatedSignalsMoodRoute
  '/_authenticated/signals/screenings': typeof AuthenticatedSignalsScreeningsRoute
  '/_authenticated/signals/sessions': typeof AuthenticatedSignalsSessionsRoute
  '/_authenticated/signals/wellbeing': typeof AuthenticatedSignalsWellbeingRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/departments'
    | '/help'
    | '/notifications'
    | '/qa'
    | '/qa-data'
    | '/reports/print'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/admin/audit'
    | '/admin/institution'
    | '/admin/members'
    | '/admin/policies'
    | '/care/capacity'
    | '/care/referrals'
    | '/care/risk'
    | '/care/routing'
    | '/cohorts/compare'
    | '/cohorts/demographics'
    | '/cohorts/programs'
    | '/cohorts/year'
    | '/reports/history'
    | '/signals/engagement'
    | '/signals/heatmap'
    | '/signals/mood'
    | '/signals/screenings'
    | '/signals/sessions'
    | '/signals/wellbeing'
    | '/admin/'
    | '/reports/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/dashboard'
    | '/departments'
    | '/help'
    | '/notifications'
    | '/qa'
    | '/qa-data'
    | '/reports/print'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/admin/audit'
    | '/admin/institution'
    | '/admin/members'
    | '/admin/policies'
    | '/care/capacity'
    | '/care/referrals'
    | '/care/risk'
    | '/care/routing'
    | '/cohorts/compare'
    | '/cohorts/demographics'
    | '/cohorts/programs'
    | '/cohorts/year'
    | '/reports/history'
    | '/signals/engagement'
    | '/signals/heatmap'
    | '/signals/mood'
    | '/signals/screenings'
    | '/signals/sessions'
    | '/signals/wellbeing'
    | '/admin'
    | '/reports'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/settings'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/departments'
    | '/_authenticated/help'
    | '/_authenticated/notifications'
    | '/_authenticated/qa'
    | '/_authenticated/qa-data'
    | '/reports/print'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/notifications'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/institution'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/policies'
    | '/_authenticated/care/capacity'
    | '/_authenticated/care/referrals'
    | '/_authenticated/care/risk'
    | '/_authenticated/care/routing'
    | '/_authenticated/cohorts/compare'
    | '/_authenticated/cohorts/demographics'
    | '/_authenticated/cohorts/programs'
    | '/_authenticated/cohorts/year'
    | '/_authenticated/reports/history'
    | '/_authenticated/signals/engagement'
    | '/_authenticated/signals/heatmap'
    | '/_authenticated/signals/mood'
    | '/_authenticated/signals/screenings'
    | '/_authenticated/signals/sessions'
    | '/_authenticated/signals/wellbeing'
    | '/_authenticated/admin/'
    | '/_authenticated/reports/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  SettingsRoute: typeof SettingsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ReportsPrintRoute: typeof ReportsPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/notifications': {
      id: '/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof SettingsNotificationsRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/account': {
      id: '/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof SettingsAccountRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/reports/print': {
      id: '/reports/print'
      path: '/reports/print'
      fullPath: '/reports/print'
      preLoaderRoute: typeof ReportsPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/qa-data': {
      id: '/_authenticated/qa-data'
      path: '/qa-data'
      fullPath: '/qa-data'
      preLoaderRoute: typeof AuthenticatedQaDataRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/qa': {
      id: '/_authenticated/qa'
      path: '/qa'
      fullPath: '/qa'
      preLoaderRoute: typeof AuthenticatedQaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help': {
      id: '/_authenticated/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AuthenticatedHelpRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/departments': {
      id: '/_authenticated/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AuthenticatedDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/signals/wellbeing': {
      id: '/_authenticated/signals/wellbeing'
      path: '/signals/wellbeing'
      fullPath: '/signals/wellbeing'
      preLoaderRoute: typeof AuthenticatedSignalsWellbeingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/sessions': {
      id: '/_authenticated/signals/sessions'
      path: '/signals/sessions'
      fullPath: '/signals/sessions'
      preLoaderRoute: typeof AuthenticatedSignalsSessionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/screenings': {
      id: '/_authenticated/signals/screenings'
      path: '/signals/screenings'
      fullPath: '/signals/screenings'
      preLoaderRoute: typeof AuthenticatedSignalsScreeningsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/mood': {
      id: '/_authenticated/signals/mood'
      path: '/signals/mood'
      fullPath: '/signals/mood'
      preLoaderRoute: typeof AuthenticatedSignalsMoodRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/heatmap': {
      id: '/_authenticated/signals/heatmap'
      path: '/signals/heatmap'
      fullPath: '/signals/heatmap'
      preLoaderRoute: typeof AuthenticatedSignalsHeatmapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/signals/engagement': {
      id: '/_authenticated/signals/engagement'
      path: '/signals/engagement'
      fullPath: '/signals/engagement'
      preLoaderRoute: typeof AuthenticatedSignalsEngagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/history': {
      id: '/_authenticated/reports/history'
      path: '/reports/history'
      fullPath: '/reports/history'
      preLoaderRoute: typeof AuthenticatedReportsHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/year': {
      id: '/_authenticated/cohorts/year'
      path: '/cohorts/year'
      fullPath: '/cohorts/year'
      preLoaderRoute: typeof AuthenticatedCohortsYearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/programs': {
      id: '/_authenticated/cohorts/programs'
      path: '/cohorts/programs'
      fullPath: '/cohorts/programs'
      preLoaderRoute: typeof AuthenticatedCohortsProgramsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/demographics': {
      id: '/_authenticated/cohorts/demographics'
      path: '/cohorts/demographics'
      fullPath: '/cohorts/demographics'
      preLoaderRoute: typeof AuthenticatedCohortsDemographicsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cohorts/compare': {
      id: '/_authenticated/cohorts/compare'
      path: '/cohorts/compare'
      fullPath: '/cohorts/compare'
      preLoaderRoute: typeof AuthenticatedCohortsCompareRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care/routing': {
      id: '/_authenticated/care/routing'
      path: '/care/routing'
      fullPath: '/care/routing'
      preLoaderRoute: typeof AuthenticatedCareRoutingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care/risk': {
      id: '/_authenticated/care/risk'
      path: '/care/risk'
      fullPath: '/care/risk'
      preLoaderRoute: typeof AuthenticatedCareRiskRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care/referrals': {
      id: '/_authenticated/care/referrals'
      path: '/care/referrals'
      fullPath: '/care/referrals'
      preLoaderRoute: typeof AuthenticatedCareReferralsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/care/capacity': {
      id: '/_authenticated/care/capacity'
      path: '/care/capacity'
      fullPath: '/care/capacity'
      preLoaderRoute: typeof AuthenticatedCareCapacityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/policies': {
      id: '/_authenticated/admin/policies'
      path: '/policies'
      fullPath: '/admin/policies'
      preLoaderRoute: typeof AuthenticatedAdminPoliciesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/institution': {
      id: '/_authenticated/admin/institution'
      path: '/institution'
      fullPath: '/admin/institution'
      preLoaderRoute: typeof AuthenticatedAdminInstitutionRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminInstitutionRoute: typeof AuthenticatedAdminInstitutionRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRoute
  AuthenticatedAdminPoliciesRoute: typeof AuthenticatedAdminPoliciesRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminInstitutionRoute: AuthenticatedAdminInstitutionRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRoute,
  AuthenticatedAdminPoliciesRoute: AuthenticatedAdminPoliciesRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDepartmentsRoute: typeof AuthenticatedDepartmentsRoute
  AuthenticatedHelpRoute: typeof AuthenticatedHelpRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedQaRoute: typeof AuthenticatedQaRoute
  AuthenticatedQaDataRoute: typeof AuthenticatedQaDataRoute
  AuthenticatedCareCapacityRoute: typeof AuthenticatedCareCapacityRoute
  AuthenticatedCareReferralsRoute: typeof AuthenticatedCareReferralsRoute
  AuthenticatedCareRiskRoute: typeof AuthenticatedCareRiskRoute
  AuthenticatedCareRoutingRoute: typeof AuthenticatedCareRoutingRoute
  AuthenticatedCohortsCompareRoute: typeof AuthenticatedCohortsCompareRoute
  AuthenticatedCohortsDemographicsRoute: typeof AuthenticatedCohortsDemographicsRoute
  AuthenticatedCohortsProgramsRoute: typeof AuthenticatedCohortsProgramsRoute
  AuthenticatedCohortsYearRoute: typeof AuthenticatedCohortsYearRoute
  AuthenticatedReportsHistoryRoute: typeof AuthenticatedReportsHistoryRoute
  AuthenticatedSignalsEngagementRoute: typeof AuthenticatedSignalsEngagementRoute
  AuthenticatedSignalsHeatmapRoute: typeof AuthenticatedSignalsHeatmapRoute
  AuthenticatedSignalsMoodRoute: typeof AuthenticatedSignalsMoodRoute
  AuthenticatedSignalsScreeningsRoute: typeof AuthenticatedSignalsScreeningsRoute
  AuthenticatedSignalsSessionsRoute: typeof AuthenticatedSignalsSessionsRoute
  AuthenticatedSignalsWellbeingRoute: typeof AuthenticatedSignalsWellbeingRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDepartmentsRoute: AuthenticatedDepartmentsRoute,
  AuthenticatedHelpRoute: AuthenticatedHelpRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedQaRoute: AuthenticatedQaRoute,
  AuthenticatedQaDataRoute: AuthenticatedQaDataRoute,
  AuthenticatedCareCapacityRoute: AuthenticatedCareCapacityRoute,
  AuthenticatedCareReferralsRoute: AuthenticatedCareReferralsRoute,
  AuthenticatedCareRiskRoute: AuthenticatedCareRiskRoute,
  AuthenticatedCareRoutingRoute: AuthenticatedCareRoutingRoute,
  AuthenticatedCohortsCompareRoute: AuthenticatedCohortsCompareRoute,
  AuthenticatedCohortsDemographicsRoute: AuthenticatedCohortsDemographicsRoute,
  AuthenticatedCohortsProgramsRoute: AuthenticatedCohortsProgramsRoute,
  AuthenticatedCohortsYearRoute: AuthenticatedCohortsYearRoute,
  AuthenticatedReportsHistoryRoute: AuthenticatedReportsHistoryRoute,
  AuthenticatedSignalsEngagementRoute: AuthenticatedSignalsEngagementRoute,
  AuthenticatedSignalsHeatmapRoute: AuthenticatedSignalsHeatmapRoute,
  AuthenticatedSignalsMoodRoute: AuthenticatedSignalsMoodRoute,
  AuthenticatedSignalsScreeningsRoute: AuthenticatedSignalsScreeningsRoute,
  AuthenticatedSignalsSessionsRoute: AuthenticatedSignalsSessionsRoute,
  AuthenticatedSignalsWellbeingRoute: AuthenticatedSignalsWellbeingRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface SettingsRouteChildren {
  SettingsAccountRoute: typeof SettingsAccountRoute
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsNotificationsRoute: typeof SettingsNotificationsRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsAccountRoute: SettingsAccountRoute,
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsNotificationsRoute: SettingsNotificationsRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  SettingsRoute: SettingsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ReportsPrintRoute: ReportsPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
